### ISSUE TITLE
Swagger response too slow for big swagger documents

### ISSUE THREAD

**Issue by oguzhankahyaoglu** [Burgyn/MMLib.SwaggerForOcelot#173]
Hello,

We are currently implementing a bff middleware ahead of our current project, which exposes a giant swagger document.

In my local environment, when I send request to existing backend swagger document directly in postman, i can get response in 1 second, whereas the ocelot's response comes in 24 seconds, which is too much. 

Wil it cause problems when we post json requests that has 2mb responses in some api's or it gets a post request that posts 2 mbs? 

Here are the current configurations and swagger documents:
[Program.txt](https://github.com/Burgyn/MMLib.SwaggerForOcelot/files/6343019/Program.txt)
[Startup.txt](https://github.com/Burgyn/MMLib.SwaggerForOcelot/files/6343020/Startup.txt)

[ocelot.json.txt](https://github.com/Burgyn/MMLib.SwaggerForOcelot/files/6343022/ocelot.json.txt)

[ppm-swagger-documents.zip](https://github.com/Burgyn/MMLib.SwaggerForOcelot/files/6343016/ppm-swagger-documents.zip)

**Comment by Burgyn** [comment]
Hi @oguzhankahyaoglu,

thanks for your issue. 
I'll look into it next week.

**Comment by oguzhankahyaoglu** [comment]
Hi @Burgyn , i suspect that u might be using a low performing string replace func maybe? since its trying to replace it...
btw, in ocelot json,u can see that i am trying to redirect all requests to the same upstream path that contains the huge swaggerdocument. in such cases, u can just skip replacing maybe?

**Comment by Burgyn** [comment]
Hi @oguzhankahyaoglu,

as workaround you can turn off swagger transformation:

```json
{
  "Key": "ppm-backend-netcore",
  "TransformByOcelotConfig": false,
  "Config": [
   {
     "Name": "ppm-backend-netcore API",
     "Version": "All",
     "Url": "https://localhost:5000/swagger/All/swagger.json"
   }]
}
```

In this case, my package will not try to transform the source document based on the ocelot configuration.

---

The problem is that my package is trying to remove all unused references from the resulting swagger schema. I'll try to refactore it, but I don't give much of a chance.

**Comment by oguzhankahyaoglu** [comment]
Since ppm-backend-core is the monolith project that we are trying to split and is behaving like a fallback service, this solved my issue; reduced loading time to 1.5 seconds.

Thanks

**Comment by Burgyn** [comment]
I am glad to hear that.

**Comment by namnik** [comment]
I have this issue too.
I used this solution `"TransformByOcelotConfig" : false`, 
this config correctly worked. But now I have a new problem: when calling my Apis into swagger, it's calling with local IP instead of calling with valid domain name.  with this config and all swagger calling throws with error: 'failed to fetch'.

`{
      "UpstreamPathTemplate": "/xxx/api/{everything}",
      "DownstreamPathTemplate": "/api/{everything}",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "xx.xx.xxx.xx" //local IP
          "Port": xxxxx
        }
      ],
      "SwaggerKey": "myAppKey",
      "RouteIsCaseSensitive": "false"
    }`

**Comment by namnik** [comment]
I have this issue too.
I used this solution `"TransformByOcelotConfig" : false`, 
this config correctly worked. But now I have a new problem: when calling my Apis into swagger, it's calling with local IP instead of calling with valid domain name.  with this config and all swagger calling throws with error: 'failed to fetch'.

`{
      "UpstreamPathTemplate": "/xxx/api/{everything}",
      "DownstreamPathTemplate": "/api/{everything}",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "xx.xx.xxx.xx" //local IP
          "Port": xxxxx
        }
      ],
      "SwaggerKey": "myAppKey",
      "RouteIsCaseSensitive": "false"
    }`
