### ISSUE TITLE
Empty json path/No operations defined in spec!

### ISSUE THREAD

**Issue by TsunamiNori** [Burgyn/MMLib.SwaggerForOcelot#180]
Hi,
I tried to use this library with Ocelot and Consul. Everything seems fine till it can't show any paths from other services.

![result](https://user-images.githubusercontent.com/8581853/125168533-36934380-e1d0-11eb-9c6d-8d78489e4595.PNG)

With Consul, I use ServiceName for service discovery. I've debugged and found out that my ServiceName became null as below
![debug1](https://user-images.githubusercontent.com/8581853/125168649-b3beb880-e1d0-11eb-9ee1-8e602385a78d.PNG)

Before
![before_transform](https://user-images.githubusercontent.com/8581853/125168736-24fe6b80-e1d1-11eb-8537-6a8495a2b5b1.PNG)

After
![after_transform](https://user-images.githubusercontent.com/8581853/125168740-26c82f00-e1d1-11eb-9906-d2c5b5f4c2f6.PNG)

[ocelot.json.txt](https://github.com/Burgyn/MMLib.SwaggerForOcelot/files/6795526/ocelot.json.txt)
[customer_json.txt](https://github.com/Burgyn/MMLib.SwaggerForOcelot/files/6795527/customer_json.txt)

**Comment by Burgyn** [comment]
Hi @TsunamiNori,

thanks for your issue. The problem is not in Consul or Service discovery. The problem is that this package tries to find paths in the documentation that are defined in ocelot configurations and throws them out if it doesn't find them. In your case, in the documentation tries to find paths starting with `/api/v1/`, but there is a path `/api/v{version}/Customer/{id}`.

I don't have the right solution. It occurs to me that you modify your documentation so that the placeholder `{version}` is not in the paths, but directly the requested version. The second option is to set the `TransformByOcelotConfig`  parameter to `false` to tell this package not to modify the source documentation according to the ocelot configuration.

```json
"SwaggerEndPoints":[
   {
      "Key":"customer",
      "TransformByOcelotConfig":false,
      "Config":[
         {
            "Name":"Customer API",
            "TakeServersFromDownstreamService":true,
            "Version":"v1",
            "Service":{
               "Name":"Customer.API",
               "Path":"/swagger/v1/swagger.json"
            }
         }
      ]
   }
]
```

**Comment by TsunamiNori** [comment]
Thank you so much @Burgyn . It's working now. I forgot about "TransformByOcelotConfig" and was thought using "TakeServersFromDownstreamService" is enough.

**Comment by Burgyn** [comment]
I'm glad I helped.

Have a nice day.
