### ISSUE TITLE
Headers from securityDefinitions are not kept

### ISSUE THREAD

**Issue by walidaziz** [Burgyn/MMLib.SwaggerForOcelot#20]
**Describe the bug**
Headers from securityDefinitions are not kept in DownStream when trying with swagger UI

**Expected behavior**
Headers from securityDefinitions should be kept in DownStream

**To Reproduce**
Having following definitions in swagger.json : 
`
"securityDefinitions": {
    "apiKey": {
      "type": "apiKey",
      "description": "API Key Authentication",
      "name": "myheader",
      "in": "header"
    }
  }
`
And following acelot.json
`
    {
      "DownstreamPathTemplate": "/api/account/connexion",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "serviceclientapi.powimo.fr",
          "Port": 80
        }
      ],
      "UpstreamPathTemplate": "/api/account/connexion",
      "UpstreamHttpMethod": [ "Post" ],
      "SwaggerKey": "orders"
    }
...
    {
      "Key": "orders",
      "Config": [
        {
          "Name": "Orders API",
          "Version": "1",
          "Url": "http://serviceclientapi.powimo.fr/swagger/docs/v1"
        }
      ]
    }
...
`

When trying on Swagger UI, "myheader" is not is not send to the backend

Thanks

**Comment by Burgyn** [comment]
Hi,
I tried investigate it.
It's look like problem directly in `Swashbuckle.AspNetCore`.

Because, when I created empty web api dotnet core project. Without `ocelot`, without `MMLib.SwaggerForOcelot`, only with `Swashbuckle.AspNetCore`. then behavior was same. `SwaggerUI` probably don't propagete apikey header to backend.

Please try write issue to Swashbuckle.AspNetCore.

Thanks

**Comment by walidaziz** [comment]
thanks. i will provide an other sample asap
